# Copyright 2016 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

[package]
name = "point_viewer"
version = "0.1.0"
authors = ["Holger Rapp <hrapp@google.com>"]

[dependencies]
clap="^2.6.0"
nom="^1.2.3"
byteorder="^0.5.3"
pbr="^0.2.1"
scoped-pool="^0.1"
iron="^0.3.0"
router="^0.1.1"
urlencoded="^0.3.0"
cgmath="^0.10.0"
walkdir="^0.1.5"
json="^0.7.0"
time="^0.1.35"
