[package]
name = "point_cloud_client"
version = "0.1.0"
edition = "2018"

[[bin]]
name = "point_cloud_client_test"
path = "src/bin/test.rs"

[dependencies]
fnv = "1.0.6"
nalgebra = "0.20.0"
num_cpus ="1.12.0"
point_viewer = { path = ".." }
point_viewer_grpc = { path = "../point_viewer_grpc" }
protobuf = "2.10.1"
structopt = "0.3.9"
